### ISSUE TITLE
您好，这种 `transform：scale ` 缩放适配方案，在地图上会有偏移的问题

### ISSUE THREAD

**Issue by cwandev** [rocyuan666/vue3-scale-box#1]
请问有什么好的办法可以解决吗？

**Comment by rocyuan666** [comment]
整体页面缩放适配后，按照缩放比例，将地图的缩放比例还原（此时会出现一个问题就是承载地图的div大小还原后，会出问题）；可以这样解决：地图div外层套一个div，外层div不还原缩放比例，超出隐藏
具体实现方案参考 examples/App.vue  已提交
