### ISSUE TITLE
什么时候能支持一下ts 版本  目前ts 打包的时候报错

### ISSUE THREAD

**Issue by MysticNo1** [rocyuan666/vue3-scale-box#5]
![1687942832608](https://github.com/rocyuan666/vue3-scale-box/assets/19720745/26c41dc7-cb75-467e-b763-9ad43403ccc1)

**Comment by rocyuan666** [comment]
暂不支持，有时间再更

**Comment by MysticNo1** [comment]
谢谢你的来信，我将尽快给你回复！
